title: 유수의 학습 노트

baseurl: "/my-blog"

remote_theme: hydecorp/hydejack@v9

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-include-cache

paginate: 5
paginate_path: "/blog/page:num"

collections:
  featured_categories:
    permalink: /:name/
    output: true
